substitutions:
  device_name: test
  friendly_name: Test

esphome:
  name: $device_name

esp32:
  board: esp32dev
  framework:
    type: arduino
    
external_components:
- source: github://hencou/esphome_components
  components: [itho, i2c_esp32, sht3xd_esp32]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
 reboot_timeout: 480min

# Enable webserver
web_server:

# Enable update Over The Air
ota:

itho:
  syssht30: enable

i2c_esp32:
- id: itho_bus

fan:
- platform: itho
  id: $device_name
  name: $friendly_name
  
select:
- platform: itho
  name: ${friendly_name} stand

sensor:
- platform: itho ##will only work when itho > syssht30: enable is configured. Otherwise use sht3xd_esp32
  temperature:
    name: ${friendly_name} temperatuur
  humidity:
    name: ${friendly_name} luchtvochtigheid
- platform: uptime
  name: ${friendly_name} uptime
  filters:
    - throttle: 300s
- platform: wifi_signal
  name: ${friendly_name} WiFi signaal
  filters:
    - delta: 0.01
    - throttle: 300s
- platform: sht3xd_esp32
  i2c_id: itho_bus
  address: 0x44
  update_interval: 10s
  temperature:
    name: ${friendly_name} sht temperatuur
    filters:
    - or:
      - delta: 1.0
      - heartbeat: 300s
  humidity:
    name: ${friendly_name} sht luchtvochtigheid
    filters:
      or:
      - delta: 1.0
      - heartbeat: 300s

button:
- platform: restart
  entity_category: config
  name: ${friendly_name} restart
  id: ${device_name}__restart

text_sensor:
- platform: version
  name: ${friendly_name} ESPHome versie
- platform: wifi_info
  ip_address:
    name: ${friendly_name} ipadres
  ssid:
    name: ${friendly_name} SSID
  bssid:
    name: ${friendly_name} BSSID
