substitutions:
  device_name: mitest1
  friendly_name: Test1

esphome:
  name: $device_name
  platform: ESP8266
  board: d1_mini
  includes:
  - milight

external_components:
- source: github://hencou/esphome_components
  components: mi
   
# Enable logging
logger:
  level: WARN

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

mi:

light:
- platform: mi
  id: light1
  name: Test1
  device_id: 0xAB01
  group_id: 1
  remote_type: rgb_cct

binary_sensor:
- platform: gpio
  id: d1
  pin:
    number: D1
    mode: INPUT_PULLUP
    inverted: True
  on_multi_click:
  - timing:
    - ON for at most 0.5s
    - OFF for at least 0.5s
    then:
      light.toggle: light1
  - timing:
    - ON for at least 1s
    then:
    - light.turn_on:
        id: light1
        brightness: 0.01
        effect: 'None'
    - while:
        condition:
          binary_sensor.is_on: d1
        then:
        - light.dim_relative:
            id: light1
            relative_brightness: 7%
        - delay: 0.3s
  - timing:
    - ON for at most 0.5s
    - OFF for at most 0.5s
    - ON for at most 0.5s
    - OFF for at least 0.5s
    then:
      light.turn_on:
        id: light1
        effect: night_mode 
  - timing:
    - ON for at most 0.5s
    - OFF for at most 0.5s
    - ON for at most 0.5s
    - OFF for at most 0.5s
    - ON for at most 0.5s
    - OFF for at least 0.5s
    then:
      light.turn_on:
        id: light1
        color_mode: COLOR_TEMPERATURE
        color_temperature: 370 mireds
        
#switch to HA version 2021.12
switch:
- platform: mi
  id: pair
  name: ${friendly_name} pair
  entity_category: config
  device_id: 0xAB01
  group_id: 1
  remote_type: rgb_cct
  command: pair
- platform: mi
  id: unpair
  name: ${friendly_name} unpair
  entity_category: config
  device_id: 0xAB01
  group_id: 1
  remote_type: rgb_cct
  command: unpair

#button possbile since HA version 2021.12
button:
- platform: mi
  id: pair
  name: ${friendly_name} pair
  device_id: 0xAB01
  group_id: 1
  remote_type: rgb_cct
  command: pair
  entity_category: config
- platform: mi
  id: unpair
  name: ${friendly_name} unpair
  device_id: 0xAB01
  group_id: 1
  remote_type: rgb_cct
  command: unpair
  entity_category: config
