substitutions:
  device_name: test
  friendly_name: Test

esphome:
  name: $device_name

esp32:
  board: esp32dev
  framework:
    type: arduino
    
external_components:
- source: github://hencou/esphome_components
  components: [itho]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
 reboot_timeout: 480min

# Enable webserver
web_server:

# Enable update Over The Air
ota:

itho:
  syssht30: enable        ##Optional, default enabled: enable or disable Itho build in sensor and automation
  syssht30_address: 0x44  ##Optional, default 0x44, I2C SHT30 sensor address
  sda: 21                 ##Optional, default to default SDA pin of ESP module (21)
  scl: 22                 ##Optional, default to default SCL pin of ESP module (22)

fan:
- platform: itho
  name: $friendly_name
  
select:
- platform: itho
  name: ${friendly_name} level

sensor:
- platform: itho
  temperature:
    name: ${friendly_name} temperatuur
  humidity:
    name: ${friendly_name} luchtvochtigheid
- platform: uptime
  name: ${friendly_name} uptime
  filters:
    - throttle: 300s
- platform: wifi_signal
  name: ${friendly_name} WiFi signaal
  filters:
    - delta: 0.01
    - throttle: 300s

button:
- platform: restart
  entity_category: config
  name: ${friendly_name} restart
- platform: safe_mode         ##Usefull when ISR calls are blocking OTA, restart in safe mode before updating
  entity_category: config
  name: ${friendly_name} safemode
  
text_sensor:
- platform: version
  name: ${friendly_name} ESPHome versie
- platform: wifi_info
  ip_address:
    name: ${friendly_name} ipadres
  ssid:
    name: ${friendly_name} SSID
  bssid:
    name: ${friendly_name} BSSID
